// Auto-generated by scripts/set-ip.js (for local dev)
const LOCAL_IP = '192.168.1.39';
const LOCAL_URL = `http://${LOCAL_IP}:5001/api`;

// Production backend URL (deployed on Render)
// Replace with your actual Render URL after deploying:  https://skillpilot-backend.onrender.com
const PRODUCTION_URL = 'https://skill-pilot-native.onrender.com/api';

// In development (__DEV__ = true) use local backend
// In production APK build (__DEV__ = false) use hosted backend
export const API_URL = __DEV__ ? LOCAL_URL : PRODUCTION_URL;
